Fixes #278: Check if files_path is set before override.
acquia/lightning pull request #279
Opened 2017-02-22 17:59 UTC by swichers

Checks if there is already a files_path set and use that instead.

2017-02-23 01:53 UTC, balsama commented
This looks good to me. Thanks. I would merge now, but I know @phenaproxima is working in the space right now. Added him as a reviewer. @phenaproxima feel free to merge.

2017-02-23 16:55 UTC, phenaproxima requested changes

2017-02-23 16:55 UTC, phenaproxima commented on tests/features/bootstrap/lightning.behat.inc
> +
Nitpick, but I can't help myself -- can the extra line after empty($existing) be removed? Once that's done, this is good to merge.

2017-02-24 02:53 UTC, swichers commented
@phenaproxima Done

2017-02-24 14:28 UTC, phenaproxima approved these changes
Nice. Thanks for putting up with me!

2017-02-24 14:29 UTC, merged