Verified that Lightning Roles is enabled before attempting Media Image role setup
acquia/lightning pull request #318
Opened 2017-03-31 17:21 UTC by DevinCarlson

After updating a profile which extends Lightning, I started seeing errors when installing Lightning Media Image.

In hook_install(), Lightning Media Image attempts to grant the 'media_creator' and 'media_manager' roles the 'access image_browser entity browser pages' permission. However, those roles may not be available as they are optional config which depends on the Lightning Roles module being installed.

It looks like changes were made to the Media, Layout and Workflow modules to accommodate the addition of the Lightning Roles module (which is great btw!), so I made similar changes to Lightning Media Image.

2017-03-31 17:26 UTC, phenaproxima requested changes
Looks pretty good, just need a few changes! :)

2017-03-31 17:26 UTC, phenaproxima commented on modules/lightning_features/lightning_media/modules/lightning_media_image/lightning_media_image.install
> + * Removed in Lightning 8.x-2.07.
There won't be a Lightning 2.07 :) The next release is 8.x-2.10.

2017-03-31 17:26 UTC, phenaproxima commented on modules/lightning_features/lightning_media/modules/lightning_media_image/lightning_media_image.install
> + * the media_creator, media_manager and creator content roles.
It's not clear from Lightning's API, but this is misphrased -- media_creator and media_manager are actual user roles that ship with Lightning Media, whereas "creator" is a meta-role that is managed by the lightning.content_roles service. So this should say "...permission to the media_creator and media_manager roles, as well as the creator content role."

2017-03-31 17:26 UTC, phenaproxima commented on modules/lightning_features/lightning_media/modules/lightning_media_image/lightning_media_image.module
> +    \Drupal::service('lightning.content_roles')
The grants to media_creator and media_manager should use user_role_grant_permissions(). Only the creator grant should use the lightning.content_roles service.

2017-03-31 20:43 UTC, danepowell commented
I ran into the same bug, can confirm that this PR fixes it. Thanks!

2017-04-01 01:13 UTC, phenaproxima approved these changes

2017-04-03 13:14 UTC, balsama commented
Timeout on twitter resource on pipelines job.

2017-04-03 13:14 UTC, merged