Verify Patched constraints
acquia/lightning pull request #361
Opened 2017-05-08 18:37 UTC by balsama

We've made the mistake a few times of adding a patch to a module without pinning it to a specific release. Then, when the patch gets committed and the maintainer makes a new release, builds fail because the patch we define no longer applies.

This PR adds a composer script that validates all patched dependencies have pinned constraints and runs that script in the .travis.yml script.

2017-05-08 20:18 UTC, balsama commented
Closing until we work out travis's problem.

2017-05-08 20:37 UTC, balsama commented
Fixed the command so that it runs within docroot

2017-05-09 12:44 UTC, phenaproxima requested changes
This is really nice. I mostly have nits.

2017-05-09 12:44 UTC, phenaproxima commented on src/Composer/PatchedConstraint.php
> +    $patched_dependencies = self::getPatchedDependencyConstraints($root_package);
Nitpick: We should generally use static, not self.

2017-05-09 12:44 UTC, phenaproxima commented on src/Composer/PatchedConstraint.php
> +      if (self::packageIsUnpinned($package)) {
We should favor static over self.

2017-05-09 12:44 UTC, phenaproxima commented on src/Composer/PatchedConstraint.php
> +  protected static function packageIsUnpinned(\Composer\Package\Link $package) {
This method is missing a description in the doc comment. Also, can the type hint be shorted to Link and used at the top of the file?

2017-05-09 12:44 UTC, phenaproxima commented on src/Composer/PatchedConstraint.php
> +    if ((!is_numeric(substr($constraint, 0, 1))) || (strpos($constraint, '|') !== FALSE) || (strpos($constraint, '*') !== FALSE)) {
Wow, this is complex. Can we use a regex instead? It would be relatively simple -- all we'd need to do is this: /^[0-9\\.]+(-alpha|beta|rc[0-9]+)?$/

2017-05-09 12:44 UTC, phenaproxima commented on composer.json
> +        "verify-patched-constraints": "Acquia\\Lightning\\Composer\\PatchedConstraint::execute"
I think this should be a pre-commit hook, but we can bikeshed on that later.

2017-05-09 17:30 UTC, balsama commented
Agree with everything including moving this to a pre-commit hook:
* Moved to git-hooks/pre-commit which will now fail if verify-patched-dependencies returns a non-zero
* Add an additional composer script (symlink) that automatically symlinks .git/hooks/pre-commit to git-hooks/pre-commit 
* Updated composer.json so that composer symlink is run on install and update

2017-05-09 18:00 UTC, phenaproxima requested changes
I don't think we need the Symlink thing to be a full-fledged Composer script. We should be able to just do this as the symlink script: ln -s -f git-hooks/pre-commit .git/hooks/pre-commit

2017-05-09 18:06 UTC, balsama commented
Fair enough. I'd prefer to add it as a phing target so that we're not duplicating the same code in the install and update sections.

2017-05-09 18:59 UTC, phenaproxima approved these changes

2017-05-09 19:00 UTC, phenaproxima commented
This looks great. I think we should merge it.

2017-05-09 20:12 UTC, merged