Make it possible to choose an image style and alt text at embed time
acquia/lightning pull request #397
Opened 2017-06-28 13:39 UTC by phenaproxima

This PR addresses https://www.drupal.org/node/2784699.

As of this PR, you can select an image style, as well as set per-embed alt and title text, when you embed an image into a CKEditor instance. This means that there is no more need to have a view mode for each image style. It's not drag-handle resizing, which would be the best option, but it's not bad either.

2017-06-28 13:42 UTC, phenaproxima commented on lightning.install
> +    $config = Config::forModule('lightning');
This is a bit of gardening, unrelated to the new functionality. lightning_core_create_config() has been gone for a long time now, so this code was fatally broken.

2017-06-28 13:43 UTC, phenaproxima commented on modules/lightning_features/lightning_core/modules/lightning_test/lightning_test.install
> -    ->setComponent('field_z_image', [
All of this was moved into the new upload_bundles_test module, which is a new test-only module that was split out so as not to cause a conflict which prevented the CKEditor media browser from being properly testable when lightning_test is turned on.

2017-06-28 13:44 UTC, phenaproxima commented on modules/lightning_features/lightning_core/src/ConfigHelper.php
> -          Unicode::substr($id, Unicode::strlen($prefix) + 1)
This turned out to have always been broken, just never tested until now.

2017-06-28 13:45 UTC, phenaproxima commented on modules/lightning_features/lightning_media/config/install/filter.format.rich_text.yml
> -      allowed_html: '<a href hreflang> <em> <strong> <cite> <blockquote cite> <code> <ul type> <ol start type> <li> <dl> <dt> <dd> <h2 id> <h3 id> <h4 id> <h5 id> <h6 id> <s> <sup> <sub> <img src alt
This change allows alt and title text to be overridden in a particular embed. See https://www.drupal.org/node/2834112

2017-06-28 13:45 UTC, phenaproxima commented on modules/lightning_features/lightning_media/lightning_media.install
> -      8004 => [
This is just gardening. Lightning update 8002 no longer does anything.

2017-06-28 13:50 UTC, phenaproxima commented on modules/upload_bundles_test
> +../tests/modules/upload_bundles_test
This is a symlink that allows upload_bundles_test to be turned on during testing. Modules are not discoverable except in certain places...go figure.

2017-06-28 13:51 UTC, phenaproxima commented on src/LightningExtension/Context/UtilityContext.behat.inc
> -  public function assertSelectorMatch($selector, $count) {
I removed this because it turns out that the Mink extension already has a step definition that does the same thing. So this counts as gardening.

2017-06-28 13:51 UTC, phenaproxima commented on tests/features/bootstrap/lightning.behat.inc
> -  public function installTestModule() {
This is replaced by TestModuleContext.

2017-06-28 13:52 UTC, phenaproxima commented on tests/features/media/browser_embed_code.feature
> +  @video @twitter @instagram @with-module:lightning_test @2c43f38c
New syntax! Now we can create smaller test modules for specific scenarios that need such scaffolding, rather than a gigantic monolith.

2017-06-28 15:01 UTC, balsama commented
Should we consider hiding the "Display as" select box? Under what circumstances would a user want to embed an image or use Media Image for something other than an image?

If we _don't_ hide it, I think we need either better labels and succinct description, or canonical documentation about what the heck it does. Drupal has a bad habit of putting options like this in interfaces without explaining them.

2017-06-28 15:10 UTC, balsama commented
When I embed an image using "Embed", save, and then edit the node, the "Display as" option for that image is set to "Media Image".

2017-06-28 15:11 UTC, balsama commented
Possible follow up:
Hide the select option and provide a way to toggle it on in config.

2017-06-28 20:26 UTC, balsama requested changes
This looks and works great. I do think that we should address the labeling issue I raised in the comments. Here's my suggestion:

* Hide the select box by default. It will still behave the same - automatically defaulting to Media Image for images and Embedded for all other bundles
* Allow users to unhide that select box through an exposed configuration option
* Update the manual update steps to account for sites which might have view-mode assigned image styles and want to continue to use that workflow.

2017-06-29 12:27 UTC, phenaproxima commented
Okay, I have added all of that, plus a little bit more test coverage. There is now a Media tab at the Lightning settings page, and it has one checkbox which determines whether "Display as" will be shown. In a completely new installation of Lightning, it will be unchecked because the new default behavior is, obviously, to hide "Display as". However, in an updated installation, it will be checked in order to preserve the previous behavior, so as to be as non-disruptive as possible.

2017-06-29 14:47 UTC, closed without merging