Add UUIDs to field storage configs
acquia/lightning pull request #400
Opened 2017-06-29 19:35 UTC by balsama

Fixes #387 from Lightning's perspective. Core still provides two field storage config definitions that don't include UUIDs (field.storage.block_content.body.yml and field.storage.node.body.yml). This adds UUIDs to all of Lightning's field storage config.

2017-06-29 19:50 UTC, danepowell approved these changes

2017-06-29 19:56 UTC, phenaproxima requested changes
I think we should probably do this for *all* of Lightning's bundled config, not just fields. Consistency matters. Additionally, we will need to fix our Phing clean-config target so that it leaves UUIDs intact, as well as update everything in tests/config (i.e., re-export with UUIDs). So this PR needs to be a whole hell of a lot bigger than 9 files changed! :)

2017-06-29 19:59 UTC, balsama commented
Just talked this over and agree with @phenaproxima. Nothing too challenging about what he's recommending, just tedious.

I'd also really like to get some clarity on why core doesn't provide UUIDs on the config it provides. There might be a perfectly good reason why we _shouldn't_ be doing this. (Or not, who knows. But I'd hate to have to revert)

2017-06-29 20:03 UTC, danepowell commented
I agree that it's suspicious that core doesn't do this. I suspect it's more out of principle (i.e. "default configuration should be as generic as possible") than real specific practical reasons.

2017-07-21 16:57 UTC, balsama commented
Closing this PR for now while we continue to discuss in #387.

2017-07-21 16:57 UTC, closed without merging