Update to 8.6.x
acquia/lightning pull request #584
Opened 2018-07-10 03:32 UTC by balsama

2018-07-13 03:38 UTC, balsama commented
Also looks like the `excluded_dependencies` key in the sub-profile generated by `lightning install` is also causing `ProfileExtensionList::computeAncestry` to crap out at line 177 where `$profile` will be an array.

2018-07-20 17:20 UTC, phenaproxima requested changes

2018-07-20 17:20 UTC, phenaproxima commented on CHANGELOG.md
> +* Drupal core has been update to 8.6.x.
"update" should be "updated".

2018-07-20 17:20 UTC, phenaproxima commented on drupal-org.make
> -libraries[cropper][type] = library
We need to restore all these libraries. Damn packaging script.

2018-07-20 17:25 UTC, phenaproxima approved these changes

2018-07-20 17:26 UTC, merged