Comment support
acquia/lightning pull request #590
Opened 2018-08-07 08:26 UTC by csirmazbendeguz

This PR provides an optional default comment type.

**These configs are copied from the standard profile.**

In the standard profile these configs are not optional, so it also adds the comment field to the article content type by default - is this something we should do (requires custom code)?

2018-08-14 09:22 UTC, csirmazbendeguz commented
This is failing for unknown reasons. It passed locally. Maybe a rerun is necessary?

2018-08-14 12:03 UTC, phenaproxima commented
The failure is due to Pathauto :) We'll have to fix Lightning Layout so that it tests Pathauto integration too. I'll deal with that; until I've got that fixed, this is blocked.

2018-08-14 12:34 UTC, phenaproxima commented
Fixed the Pathauto integration in Lightning Layout, so we should be able to rerun these now.

2018-08-14 16:48 UTC, phenaproxima commented
Okay, so -- to get this working, I need you to make a small change to lightning.profile. In `lightning_modules_installed()`, you'll see this:

```php
    entity_create('node_type', [
      'type' => 'article',
      'name' => 'Article',
    ])->save();
```

This should be removed; Lightning Workflow now creates that content type for testing when Lightning Dev is enabled.

2018-08-15 08:50 UTC, csirmazbendeguz commented
Done. This fixes the assertion that fails: https://github.com/acquia/lightning-media/pull/45

2018-08-15 12:06 UTC, phenaproxima commented
So one question I have here, is why did the media assertion fail for only two of five builds? It should have failed for all of them, I'd think...

2018-08-15 12:09 UTC, phenaproxima requested changes

2018-08-15 12:09 UTC, phenaproxima commented on tests/src/Functional/DefaultCommentTypeTest.php
> +class DefaultCommentTypeTest extends BrowserTestBase {
Thank you for writing this test, but I think we can actually remove it. I say that for two reasons: first, it installs Lightning, which will make it incredibly slow; and second, it's really just testing the optional config system in core, which is already very well-covered by core's tests. So there's no need for it here. :)

2018-08-15 12:46 UTC, csirmazbendeguz commented
It seems like pathauto is not getting enabled.

2018-08-15 13:06 UTC, phenaproxima approved these changes

2018-08-15 14:29 UTC, merged

2018-08-15 14:30 UTC, phenaproxima commented
Looks good to me. Let's not bother adding comments to any specific node types right now; that could be a can of worms we don't want to get into. But at least we now have the basics of Comment support in place. Thanks, Bendi!